/* Generated by gbrecomp from gfxtest */
#include "gfxtest.h"
#include "gbrt.h"

/* Forward declarations */
static void gb_main(GBContext* ctx);
static void int_joypad(GBContext* ctx);
static void int_lcd_stat(GBContext* ctx);
static void int_serial(GBContext* ctx);
static void int_timer(GBContext* ctx);
static void int_vblank(GBContext* ctx);
static void rst_00(GBContext* ctx);
static void rst_08(GBContext* ctx);
static void rst_10(GBContext* ctx);
static void rst_18(GBContext* ctx);
static void rst_20(GBContext* ctx);
static void rst_28(GBContext* ctx);
static void rst_30(GBContext* ctx);
static void rst_38(GBContext* ctx);

/* Bank dispatch - routes calls to the correct bank function */
void gb_dispatch(GBContext* ctx, uint16_t addr) {
    uint8_t bank = ctx->rom_bank;
    if (addr < 0x4000) bank = 0;
    switch (addr) {
        case 0x0000:
            rst_00(ctx); return;
        case 0x0008:
            rst_08(ctx); return;
        case 0x0010:
            rst_10(ctx); return;
        case 0x0018:
            rst_18(ctx); return;
        case 0x0020:
            rst_20(ctx); return;
        case 0x0028:
            rst_28(ctx); return;
        case 0x0030:
            rst_30(ctx); return;
        case 0x0038:
            rst_38(ctx); return;
        case 0x0040:
            int_vblank(ctx); return;
        case 0x0048:
            int_lcd_stat(ctx); return;
        case 0x0050:
            int_timer(ctx); return;
        case 0x0058:
            int_serial(ctx); return;
        case 0x0060:
            int_joypad(ctx); return;
        case 0x0100:
            gb_main(ctx); return;
        default: return;
    }
}

void gb_dispatch_call(GBContext* ctx, uint16_t addr) {
    gb_dispatch(ctx, addr);
}

/* Function at 0100 */
static void gb_main(GBContext* ctx) {
loc_0100:
    /* 0100 */     /* NOP */
    /* 0100 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0101 */     /* JP nn */
    /* 0101 */     goto loc_0150;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
loc_0150:
    /* 0150 */     /* LD rr,nn */
    /* 0150 */     ctx->sp = 0xfffe;
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 0153 */     /* DI */
    /* 0153 */     ctx->ime = 0;
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
loc_0154:
    /* 0154 */     /* LDH A,(n) */
    /* 0154 */     ctx->a = gb_read8(ctx, 0xff44);
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 0156 */     /* ??? */
    /* 0156 */     gb_cp8(ctx, 0x90);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0158 */     /* JR cc,n */
    /* 0158 */     if (!ctx->f_z) goto loc_0154; /* NZ */
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_015a:
    /* 015a */     /* LD r,n */
    /* 015a */     ctx->a = 0x00;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 015c */     /* LDH (n),A */
    /* 015c */     gb_write8(ctx, 0xff40, ctx->a);
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 015e */     /* LD rr,nn */
    /* 015e */     ctx->hl = 0x8000;
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 0161 */     /* LD rr,nn */
    /* 0161 */     ctx->de = 0x1000;
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 0164 */     /* LD rr,nn */
    /* 0164 */     ctx->bc = 0x0050;
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
loc_0167:
    /* 0167 */     /* LD A,(DE) */
    /* 0167 */     ctx->a = gb_read8(ctx, ctx->de);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0168 */     /* LD (HL+),A */
    /* 0168 */     gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0168 */     ctx->hl++;
    /* 0169 */     /* ??? */
    /* 0169 */     ctx->de++;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 016a */     /* ??? */
    /* 016a */     ctx->bc--;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 016b */     /* LD r,r */
    /* 016b */     ctx->a = ctx->b;
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 016c */     /* ??? */
    /* 016c */     gb_or8(ctx, ctx->c);
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 016d */     /* JR cc,n */
    /* 016d */     if (!ctx->f_z) goto loc_0167; /* NZ */
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_016f:
    /* 016f */     /* LD rr,nn */
    /* 016f */     ctx->hl = 0x9800;
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
loc_0172:
    /* 0172 */     /* LD r,n */
    /* 0172 */     ctx->b = 0x12;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0174 */     /* LD r,n */
    /* 0174 */     ctx->c = 0x14;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0176 */     /* LD r,n */
    /* 0176 */     ctx->d = 0x00;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_0178:
    /* 0178 */     /* LD r,r */
    /* 0178 */     ctx->a = ctx->d;
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0179 */     /* ??? */
    /* 0179 */     gb_and8(ctx, 0x04);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 017b */     /* LD (HL+),A */
    /* 017b */     gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 017b */     ctx->hl++;
    /* 017c */     /* ??? */
    /* 017c */     ctx->d = gb_inc8(ctx, ctx->d);
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 017d */     /* ??? */
    /* 017d */     ctx->c = gb_dec8(ctx, ctx->c);
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 017e */     /* JR cc,n */
    /* 017e */     if (!ctx->f_z) goto loc_0178; /* NZ */
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_0180:
    /* 0180 */     /* LD rr,nn */
    /* 0180 */     ctx->de = 0x000c;
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 0183 */     /* ADD HL,rr */
    /* 0183 */     gb_add16(ctx, ctx->de);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0184 */     /* ??? */
    /* 0184 */     ctx->b = gb_dec8(ctx, ctx->b);
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0185 */     /* JR cc,n */
    /* 0185 */     if (!ctx->f_z) goto loc_0172; /* NZ */
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_0187:
    /* 0187 */     /* LD r,n */
    /* 0187 */     ctx->a = 0xe4;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0189 */     /* LDH (n),A */
    /* 0189 */     gb_write8(ctx, 0xff47, ctx->a);
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 018b */     /* LD r,n */
    /* 018b */     ctx->a = 0x00;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 018d */     /* LDH (n),A */
    /* 018d */     gb_write8(ctx, 0xff42, ctx->a);
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 018f */     /* LDH (n),A */
    /* 018f */     gb_write8(ctx, 0xff43, ctx->a);
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
loc_0191:
    /* 0191 */     /* LD r,n */
    /* 0191 */     ctx->a = 0x91;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0193 */     /* LDH (n),A */
    /* 0193 */     gb_write8(ctx, 0xff40, ctx->a);
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
loc_0195:
    /* 0195 */     /* LDH A,(n) */
    /* 0195 */     ctx->a = gb_read8(ctx, 0xff44);
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 0197 */     /* ??? */
    /* 0197 */     gb_cp8(ctx, 0x90);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0199 */     /* JR cc,n */
    /* 0199 */     if (!ctx->f_z) goto loc_0195; /* NZ */
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_019b:
    /* 019b */     /* LDH A,(n) */
    /* 019b */     ctx->a = gb_read8(ctx, 0xff44);
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 019d */     /* ??? */
    /* 019d */     gb_cp8(ctx, 0x90);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 019f */     /* JR cc,n */
    /* 019f */     if (ctx->f_z) goto loc_019b; /* Z */
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_01a1:
    /* 01a1 */     /* JR n */
    /* 01a1 */     goto loc_0191;
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
}

/* Function at 0060 */
static void int_joypad(GBContext* ctx) {
loc_0060:
    /* 0060 */     /* RETI */
    /* 0060 */     ctx->ime = 1; return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0048 */
static void int_lcd_stat(GBContext* ctx) {
loc_0048:
    /* 0048 */     /* RETI */
    /* 0048 */     ctx->ime = 1; return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0058 */
static void int_serial(GBContext* ctx) {
loc_0058:
    /* 0058 */     /* RETI */
    /* 0058 */     ctx->ime = 1; return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0050 */
static void int_timer(GBContext* ctx) {
loc_0050:
    /* 0050 */     /* RETI */
    /* 0050 */     ctx->ime = 1; return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0040 */
static void int_vblank(GBContext* ctx) {
loc_0040:
    /* 0040 */     /* RETI */
    /* 0040 */     ctx->ime = 1; return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0000 */
static void rst_00(GBContext* ctx) {
loc_0000:
    /* RET */
    return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0008 */
static void rst_08(GBContext* ctx) {
loc_0008:
    /* 0008 */     /* RET */
    /* 0008 */     return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0010 */
static void rst_10(GBContext* ctx) {
loc_0010:
    /* 0010 */     /* RET */
    /* 0010 */     return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0018 */
static void rst_18(GBContext* ctx) {
loc_0018:
    /* 0018 */     /* RET */
    /* 0018 */     return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0020 */
static void rst_20(GBContext* ctx) {
loc_0020:
    /* 0020 */     /* RET */
    /* 0020 */     return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0028 */
static void rst_28(GBContext* ctx) {
loc_0028:
    /* 0028 */     /* RET */
    /* 0028 */     return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0030 */
static void rst_30(GBContext* ctx) {
loc_0030:
    /* 0030 */     /* RET */
    /* 0030 */     return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Function at 0038 */
static void rst_38(GBContext* ctx) {
loc_0038:
    /* 0038 */     /* RET */
    /* 0038 */     return;
    gb_tick(ctx, 16);
    if (ctx->stopped) return;
}

/* Extern reference to ROM data */
extern const uint8_t rom_data[];

void gfxtest_init(GBContext* ctx) {
    /* Load ROM data into context */
    gb_context_load_rom(ctx, rom_data, 32768);
}

void gfxtest_run(GBContext* ctx) {
    gb_main(ctx);
}
