/* Generated by gbrecomp from 01-special */
#include "_01_special.h"
#include "gbrt.h"

/* Forward declarations */
static void func_01_4000(GBContext* ctx);
static void gb_main(GBContext* ctx);
static void int_joypad(GBContext* ctx);
static void int_lcd_stat(GBContext* ctx);
static void int_serial(GBContext* ctx);
static void int_timer(GBContext* ctx);
static void int_vblank(GBContext* ctx);
static void rst_00(GBContext* ctx);
static void rst_08(GBContext* ctx);
static void rst_10(GBContext* ctx);
static void rst_18(GBContext* ctx);
static void rst_20(GBContext* ctx);
static void rst_28(GBContext* ctx);
static void rst_30(GBContext* ctx);
static void rst_38(GBContext* ctx);

/* Bank dispatch - routes calls to the correct bank function */
void gb_dispatch(GBContext* ctx, uint16_t addr) {
    ctx->pc = addr;
    while (!ctx->stopped) {
        addr = ctx->pc;
        uint8_t bank = ctx->rom_bank;
        if (addr < 0x4000) bank = 0;
        switch (addr) {
            case 0x0000:
                rst_00(ctx); break;
            case 0x0008:
                rst_08(ctx); break;
            case 0x0010:
                rst_10(ctx); break;
            case 0x0018:
                rst_18(ctx); break;
            case 0x0020:
                rst_20(ctx); break;
            case 0x0028:
                rst_28(ctx); break;
            case 0x0030:
                rst_30(ctx); break;
            case 0x0038:
                rst_38(ctx); break;
            case 0x0040:
                int_vblank(ctx); break;
            case 0x0048:
                int_lcd_stat(ctx); break;
            case 0x0050:
                int_timer(ctx); break;
            case 0x0058:
                int_serial(ctx); break;
            case 0x0060:
                int_joypad(ctx); break;
            case 0x0100:
                gb_main(ctx); break;
            case 0x0200:
                gb_main(ctx); break;
            case 0x0206:
                gb_main(ctx); break;
            case 0x020b:
                gb_main(ctx); break;
            case 0x020f:
                gb_main(ctx); break;
            case 0x0213:
                gb_main(ctx); break;
            case 0x4000:
                func_01_4000(ctx); break;
            default: gb_interpret(ctx, addr); break;
        }
    }
}

void gb_dispatch_call(GBContext* ctx, uint16_t addr) {
    gb_dispatch(ctx, addr);
}

/* Function at 01:4000 */
static void func_01_4000(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x4000: goto loc_4000;
        default: break;
    }

loc_4000:
    /* 01:4000 */     /* JP $c220 */
    /* 01:4000 */     gb_tick(ctx, 16);
    gb_dispatch(ctx, 0xc220); return;
}

/* Function at 0100 */
static void gb_main(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0100: goto loc_0100;
        case 0x0200: goto loc_0200;
        case 0x0206: goto loc_0206;
        case 0x020b: goto loc_020b;
        case 0x020f: goto loc_020f;
        case 0x0213: goto loc_0213;
        default: break;
    }

loc_0100:
    /* 0100 */     /* NOP */
    /* 0100 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0101 */     /* JP $0213 */
    /* 0101 */     gb_tick(ctx, 16);
    if (ctx->stopped) return;
    goto loc_0213;
loc_0200:
    /* 0200 */     /* LD B,A */
    /* 0200 */     ctx->b = ctx->a;
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0201 */     /* LD DE,$c000 */
    /* 0201 */     ctx->de = 0xc000;
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 0204 */     /* LD C,$10 */
    /* 0204 */     ctx->c = 0x10;
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_0206:
    /* 0206 */     /* LD A,(HL+) */
    /* 0206 */     ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0206 */     ctx->hl++;
    /* 0207 */     /* LD (DE),A */
    /* 0207 */     gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
    /* 0208 */     /* INC E */
    /* 0208 */     ctx->e = gb_inc8(ctx, ctx->e);
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0209 */     /* JR NZ,-5 */
    /* 0209 */     if (!ctx->f_z) goto loc_0206; /* NZ */
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_020b:
    /* 020b */     /* INC D */
    /* 020b */     ctx->d = gb_inc8(ctx, ctx->d);
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 020c */     /* DEC C */
    /* 020c */     ctx->c = gb_dec8(ctx, ctx->c);
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 020d */     /* JR NZ,-9 */
    /* 020d */     if (!ctx->f_z) goto loc_0206; /* NZ */
    gb_tick(ctx, 8);
    if (ctx->stopped) return;
loc_020f:
    /* 020f */     /* LD A,B */
    /* 020f */     ctx->a = ctx->b;
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0210 */     /* JP $c000 */
    /* 0210 */     gb_tick(ctx, 16);
    gb_dispatch(ctx, 0xc000); return;
loc_0213:
    /* 0213 */     /* LD HL,$4000 */
    /* 0213 */     ctx->hl = 0x4000;
    gb_tick(ctx, 12);
    if (ctx->stopped) return;
    /* 0216 */     /* JP $0200 */
    /* 0216 */     gb_tick(ctx, 16);
    if (ctx->stopped) return;
    goto loc_0200;
}

/* Function at 0060 */
static void int_joypad(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0060: goto loc_0060;
        default: break;
    }

loc_0060:
    /* 0060 */     /* NOP */
    /* 0060 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0061 */     /* NOP */
    /* 0061 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0062 */     /* NOP */
    /* 0062 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0063 */     /* NOP */
    /* 0063 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0064 */     /* NOP */
    /* 0064 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0065 */     /* NOP */
    /* 0065 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0066 */     /* NOP */
    /* 0066 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0067 */     /* NOP */
    /* 0067 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0068 */     /* NOP */
    /* 0068 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0069 */     /* NOP */
    /* 0069 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 006a */     /* NOP */
    /* 006a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 006b */     /* NOP */
    /* 006b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 006c */     /* NOP */
    /* 006c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 006d */     /* NOP */
    /* 006d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 006e */     /* NOP */
    /* 006e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 006f */     /* NOP */
    /* 006f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0070 */     /* NOP */
    /* 0070 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0071 */     /* NOP */
    /* 0071 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0072 */     /* NOP */
    /* 0072 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0073 */     /* NOP */
    /* 0073 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0074 */     /* NOP */
    /* 0074 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0075 */     /* NOP */
    /* 0075 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0076 */     /* NOP */
    /* 0076 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0077 */     /* NOP */
    /* 0077 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0078 */     /* NOP */
    /* 0078 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0079 */     /* NOP */
    /* 0079 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 007a */     /* NOP */
    /* 007a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 007b */     /* NOP */
    /* 007b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 007c */     /* NOP */
    /* 007c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 007d */     /* NOP */
    /* 007d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 007e */     /* NOP */
    /* 007e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 007f */     /* NOP */
    /* 007f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0080 */     /* NOP */
    /* 0080 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0081 */     /* NOP */
    /* 0081 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0082 */     /* NOP */
    /* 0082 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0083 */     /* NOP */
    /* 0083 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0084 */     /* NOP */
    /* 0084 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0085 */     /* NOP */
    /* 0085 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0086 */     /* NOP */
    /* 0086 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0087 */     /* NOP */
    /* 0087 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0088 */     /* NOP */
    /* 0088 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0089 */     /* NOP */
    /* 0089 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 008a */     /* NOP */
    /* 008a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 008b */     /* NOP */
    /* 008b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 008c */     /* NOP */
    /* 008c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 008d */     /* NOP */
    /* 008d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 008e */     /* NOP */
    /* 008e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 008f */     /* NOP */
    /* 008f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0090 */     /* NOP */
    /* 0090 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0091 */     /* NOP */
    /* 0091 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0092 */     /* NOP */
    /* 0092 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0093 */     /* NOP */
    /* 0093 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0094 */     /* NOP */
    /* 0094 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0095 */     /* NOP */
    /* 0095 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0096 */     /* NOP */
    /* 0096 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0097 */     /* NOP */
    /* 0097 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0098 */     /* NOP */
    /* 0098 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0099 */     /* NOP */
    /* 0099 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 009a */     /* NOP */
    /* 009a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 009b */     /* NOP */
    /* 009b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 009c */     /* NOP */
    /* 009c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 009d */     /* NOP */
    /* 009d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 009e */     /* NOP */
    /* 009e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 009f */     /* NOP */
    /* 009f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a0 */     /* NOP */
    /* 00a0 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a1 */     /* NOP */
    /* 00a1 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a2 */     /* NOP */
    /* 00a2 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a3 */     /* NOP */
    /* 00a3 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a4 */     /* NOP */
    /* 00a4 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a5 */     /* NOP */
    /* 00a5 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a6 */     /* NOP */
    /* 00a6 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a7 */     /* NOP */
    /* 00a7 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a8 */     /* NOP */
    /* 00a8 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00a9 */     /* NOP */
    /* 00a9 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00aa */     /* NOP */
    /* 00aa */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ab */     /* NOP */
    /* 00ab */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ac */     /* NOP */
    /* 00ac */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ad */     /* NOP */
    /* 00ad */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ae */     /* NOP */
    /* 00ae */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00af */     /* NOP */
    /* 00af */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b0 */     /* NOP */
    /* 00b0 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b1 */     /* NOP */
    /* 00b1 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b2 */     /* NOP */
    /* 00b2 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b3 */     /* NOP */
    /* 00b3 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b4 */     /* NOP */
    /* 00b4 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b5 */     /* NOP */
    /* 00b5 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b6 */     /* NOP */
    /* 00b6 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b7 */     /* NOP */
    /* 00b7 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b8 */     /* NOP */
    /* 00b8 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00b9 */     /* NOP */
    /* 00b9 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ba */     /* NOP */
    /* 00ba */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00bb */     /* NOP */
    /* 00bb */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00bc */     /* NOP */
    /* 00bc */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00bd */     /* NOP */
    /* 00bd */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00be */     /* NOP */
    /* 00be */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00bf */     /* NOP */
    /* 00bf */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c0 */     /* NOP */
    /* 00c0 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c1 */     /* NOP */
    /* 00c1 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c2 */     /* NOP */
    /* 00c2 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c3 */     /* NOP */
    /* 00c3 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c4 */     /* NOP */
    /* 00c4 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c5 */     /* NOP */
    /* 00c5 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c6 */     /* NOP */
    /* 00c6 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c7 */     /* NOP */
    /* 00c7 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c8 */     /* NOP */
    /* 00c8 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00c9 */     /* NOP */
    /* 00c9 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ca */     /* NOP */
    /* 00ca */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00cb */     /* NOP */
    /* 00cb */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00cc */     /* NOP */
    /* 00cc */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00cd */     /* NOP */
    /* 00cd */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ce */     /* NOP */
    /* 00ce */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00cf */     /* NOP */
    /* 00cf */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d0 */     /* NOP */
    /* 00d0 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d1 */     /* NOP */
    /* 00d1 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d2 */     /* NOP */
    /* 00d2 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d3 */     /* NOP */
    /* 00d3 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d4 */     /* NOP */
    /* 00d4 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d5 */     /* NOP */
    /* 00d5 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d6 */     /* NOP */
    /* 00d6 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d7 */     /* NOP */
    /* 00d7 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d8 */     /* NOP */
    /* 00d8 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00d9 */     /* NOP */
    /* 00d9 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00da */     /* NOP */
    /* 00da */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00db */     /* NOP */
    /* 00db */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00dc */     /* NOP */
    /* 00dc */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00dd */     /* NOP */
    /* 00dd */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00de */     /* NOP */
    /* 00de */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00df */     /* NOP */
    /* 00df */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e0 */     /* NOP */
    /* 00e0 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e1 */     /* NOP */
    /* 00e1 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e2 */     /* NOP */
    /* 00e2 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e3 */     /* NOP */
    /* 00e3 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e4 */     /* NOP */
    /* 00e4 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e5 */     /* NOP */
    /* 00e5 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e6 */     /* NOP */
    /* 00e6 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e7 */     /* NOP */
    /* 00e7 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e8 */     /* NOP */
    /* 00e8 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00e9 */     /* NOP */
    /* 00e9 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ea */     /* NOP */
    /* 00ea */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00eb */     /* NOP */
    /* 00eb */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ec */     /* NOP */
    /* 00ec */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ed */     /* NOP */
    /* 00ed */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ee */     /* NOP */
    /* 00ee */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ef */     /* NOP */
    /* 00ef */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f0 */     /* NOP */
    /* 00f0 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f1 */     /* NOP */
    /* 00f1 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f2 */     /* NOP */
    /* 00f2 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f3 */     /* NOP */
    /* 00f3 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f4 */     /* NOP */
    /* 00f4 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f5 */     /* NOP */
    /* 00f5 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f6 */     /* NOP */
    /* 00f6 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f7 */     /* NOP */
    /* 00f7 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f8 */     /* NOP */
    /* 00f8 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00f9 */     /* NOP */
    /* 00f9 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00fa */     /* NOP */
    /* 00fa */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00fb */     /* NOP */
    /* 00fb */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00fc */     /* NOP */
    /* 00fc */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00fd */     /* NOP */
    /* 00fd */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00fe */     /* NOP */
    /* 00fe */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 00ff */     /* NOP */
    /* 00ff */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    gb_main(ctx);
    return;
}

/* Function at 0048 */
static void int_lcd_stat(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0048: goto loc_0048;
        default: break;
    }

loc_0048:
    /* 0048 */     /* NOP */
    /* 0048 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0049 */     /* NOP */
    /* 0049 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 004a */     /* NOP */
    /* 004a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 004b */     /* NOP */
    /* 004b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 004c */     /* NOP */
    /* 004c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 004d */     /* NOP */
    /* 004d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 004e */     /* NOP */
    /* 004e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 004f */     /* NOP */
    /* 004f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    int_timer(ctx);
    return;
}

/* Function at 0058 */
static void int_serial(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0058: goto loc_0058;
        default: break;
    }

loc_0058:
    /* 0058 */     /* NOP */
    /* 0058 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0059 */     /* NOP */
    /* 0059 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 005a */     /* NOP */
    /* 005a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 005b */     /* NOP */
    /* 005b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 005c */     /* NOP */
    /* 005c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 005d */     /* NOP */
    /* 005d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 005e */     /* NOP */
    /* 005e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 005f */     /* NOP */
    /* 005f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    int_joypad(ctx);
    return;
}

/* Function at 0050 */
static void int_timer(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0050: goto loc_0050;
        default: break;
    }

loc_0050:
    /* 0050 */     /* NOP */
    /* 0050 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0051 */     /* NOP */
    /* 0051 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0052 */     /* NOP */
    /* 0052 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0053 */     /* NOP */
    /* 0053 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0054 */     /* NOP */
    /* 0054 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0055 */     /* NOP */
    /* 0055 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0056 */     /* NOP */
    /* 0056 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0057 */     /* NOP */
    /* 0057 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    int_serial(ctx);
    return;
}

/* Function at 0040 */
static void int_vblank(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0040: goto loc_0040;
        default: break;
    }

loc_0040:
    /* 0040 */     /* NOP */
    /* 0040 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0041 */     /* NOP */
    /* 0041 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0042 */     /* NOP */
    /* 0042 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0043 */     /* NOP */
    /* 0043 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0044 */     /* NOP */
    /* 0044 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0045 */     /* NOP */
    /* 0045 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0046 */     /* NOP */
    /* 0046 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0047 */     /* NOP */
    /* 0047 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    int_lcd_stat(ctx);
    return;
}

/* Function at 0000 */
static void rst_00(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0000: goto loc_0000;
        default: break;
    }

loc_0000:
    /* NOP */
    /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0001 */     /* NOP */
    /* 0001 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0002 */     /* NOP */
    /* 0002 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0003 */     /* NOP */
    /* 0003 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0004 */     /* NOP */
    /* 0004 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0005 */     /* NOP */
    /* 0005 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0006 */     /* NOP */
    /* 0006 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0007 */     /* NOP */
    /* 0007 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    rst_08(ctx);
    return;
}

/* Function at 0008 */
static void rst_08(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0008: goto loc_0008;
        default: break;
    }

loc_0008:
    /* 0008 */     /* NOP */
    /* 0008 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0009 */     /* NOP */
    /* 0009 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 000a */     /* NOP */
    /* 000a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 000b */     /* NOP */
    /* 000b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 000c */     /* NOP */
    /* 000c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 000d */     /* NOP */
    /* 000d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 000e */     /* NOP */
    /* 000e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 000f */     /* NOP */
    /* 000f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    rst_10(ctx);
    return;
}

/* Function at 0010 */
static void rst_10(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0010: goto loc_0010;
        default: break;
    }

loc_0010:
    /* 0010 */     /* NOP */
    /* 0010 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0011 */     /* NOP */
    /* 0011 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0012 */     /* NOP */
    /* 0012 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0013 */     /* NOP */
    /* 0013 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0014 */     /* NOP */
    /* 0014 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0015 */     /* NOP */
    /* 0015 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0016 */     /* NOP */
    /* 0016 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0017 */     /* NOP */
    /* 0017 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    rst_18(ctx);
    return;
}

/* Function at 0018 */
static void rst_18(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0018: goto loc_0018;
        default: break;
    }

loc_0018:
    /* 0018 */     /* NOP */
    /* 0018 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0019 */     /* NOP */
    /* 0019 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 001a */     /* NOP */
    /* 001a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 001b */     /* NOP */
    /* 001b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 001c */     /* NOP */
    /* 001c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 001d */     /* NOP */
    /* 001d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 001e */     /* NOP */
    /* 001e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 001f */     /* NOP */
    /* 001f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    rst_20(ctx);
    return;
}

/* Function at 0020 */
static void rst_20(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0020: goto loc_0020;
        default: break;
    }

loc_0020:
    /* 0020 */     /* NOP */
    /* 0020 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0021 */     /* NOP */
    /* 0021 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0022 */     /* NOP */
    /* 0022 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0023 */     /* NOP */
    /* 0023 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0024 */     /* NOP */
    /* 0024 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0025 */     /* NOP */
    /* 0025 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0026 */     /* NOP */
    /* 0026 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0027 */     /* NOP */
    /* 0027 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    rst_28(ctx);
    return;
}

/* Function at 0028 */
static void rst_28(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0028: goto loc_0028;
        default: break;
    }

loc_0028:
    /* 0028 */     /* NOP */
    /* 0028 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0029 */     /* NOP */
    /* 0029 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 002a */     /* NOP */
    /* 002a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 002b */     /* NOP */
    /* 002b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 002c */     /* NOP */
    /* 002c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 002d */     /* NOP */
    /* 002d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 002e */     /* NOP */
    /* 002e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 002f */     /* NOP */
    /* 002f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    rst_30(ctx);
    return;
}

/* Function at 0030 */
static void rst_30(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0030: goto loc_0030;
        default: break;
    }

loc_0030:
    /* 0030 */     /* NOP */
    /* 0030 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0031 */     /* NOP */
    /* 0031 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0032 */     /* NOP */
    /* 0032 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0033 */     /* NOP */
    /* 0033 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0034 */     /* NOP */
    /* 0034 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0035 */     /* NOP */
    /* 0035 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0036 */     /* NOP */
    /* 0036 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0037 */     /* NOP */
    /* 0037 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    rst_38(ctx);
    return;
}

/* Function at 0038 */
static void rst_38(GBContext* ctx) {
    switch (ctx->pc) {
        case 0x0038: goto loc_0038;
        default: break;
    }

loc_0038:
    /* 0038 */     /* NOP */
    /* 0038 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 0039 */     /* NOP */
    /* 0039 */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 003a */     /* NOP */
    /* 003a */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 003b */     /* NOP */
    /* 003b */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 003c */     /* NOP */
    /* 003c */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 003d */     /* NOP */
    /* 003d */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 003e */     /* NOP */
    /* 003e */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* 003f */     /* NOP */
    /* 003f */     /* NOP */
    gb_tick(ctx, 4);
    if (ctx->stopped) return;
    /* fallthrough to function */
    int_vblank(ctx);
    return;
}

/* Extern reference to ROM data */
extern const uint8_t rom_data[];

void _01_special_init(GBContext* ctx) {
    /* Load ROM data into context */
    gb_context_load_rom(ctx, rom_data, 32768);
}

void _01_special_run(GBContext* ctx) {
    // Start the trampoline loop - execution will stay here until stopped
    gb_dispatch(ctx, ctx->pc);
}
