#include "recompiler/symbol_table.h"

#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

struct TempDirectory {
    fs::path path;

    TempDirectory() {
        const auto nonce =
            std::chrono::steady_clock::now().time_since_epoch().count();
        path = fs::temp_directory_path() /
               ("gbrecomp-rgbds-symbol-test-" + std::to_string(nonce));
        fs::create_directories(path);
    }

    ~TempDirectory() {
        std::error_code error;
        fs::remove_all(path, error);
    }
};

fs::path write_fixture(const fs::path& directory,
                       const std::string& name,
                       const std::string& contents) {
    const fs::path path = directory / name;
    std::ofstream file(path);
    file << contents;
    file.close();
    return path;
}

bool expect_rejected(const fs::path& directory,
                     const std::string& name,
                     const std::string& contents,
                     const std::string& expected_error) {
    gbrecomp::SymbolTable table;
    std::string error;
    if (table.load_sym_file(
            write_fixture(directory, name, contents).string(), nullptr, &error)) {
        std::cerr << name << " unexpectedly passed\n";
        return false;
    }
    if (error.find(expected_error) == std::string::npos) {
        std::cerr << name << " error did not contain '" << expected_error
                  << "': " << error << "\n";
        return false;
    }
    if (table.size() != 0 || table.constant_count() != 0) {
        std::cerr << name << " left partial parser state\n";
        return false;
    }
    return true;
}

bool expect_annotation_rejected(const fs::path& directory,
                                const std::string& name,
                                const std::string& contents,
                                const std::string& expected_error) {
    gbrecomp::SymbolTable table;
    std::string error;
    if (table.load_annotation_file(
            write_fixture(directory, name, contents).string(), &error)) {
        std::cerr << name << " unexpectedly passed\n";
        return false;
    }
    if (error.find(expected_error) == std::string::npos) {
        std::cerr << name << " error did not contain '" << expected_error
                  << "': " << error << "\n";
        return false;
    }
    return true;
}

} // namespace

int main() {
    TempDirectory temporary;
    const fs::path valid = write_fixture(
        temporary.path,
        "valid.sym",
        "; File generated by rgblink\n"
        "00:0100 Start\n"
        "00:0100 EntryAlias\n"
        "00:c000 wPlayerData ; retained RAM comment\n"
        "01:d000 wBankedData\n"
        "2a ANSWER ; retained constant comment\n"
        "00 SCENE_ZERO\n"
        "00 SCENE_ZERO\n");

    gbrecomp::SymbolTable table;
    std::string error;
    if (!table.load_sym_file(valid.string(), nullptr, &error)) {
        std::cerr << "valid RGBDS fixture failed: " << error << "\n";
        return 1;
    }

    const gbrecomp::SymbolLoadStats& stats = table.load_stats();
    if (stats.address_records != 4 ||
        stats.unique_addresses != 3 ||
        stats.duplicate_address_records != 1 ||
        stats.constant_records != 3 ||
        stats.unique_constants != 2 ||
        stats.duplicate_constant_records != 1) {
        std::cerr << "unexpected parser statistics\n";
        return 1;
    }
    if (table.size() != 3 || table.constant_count() != 2) {
        std::cerr << "constants were confused with address symbols\n";
        return 1;
    }

    const gbrecomp::RGBDSConstant* answer = table.get_constant("ANSWER");
    const gbrecomp::RGBDSConstant* scene = table.get_constant("SCENE_ZERO");
    if (!answer || answer->value != 0x2A || !scene || scene->value != 0) {
        std::cerr << "constant values were not parsed as RGBDS hexadecimal\n";
        return 1;
    }
    if (answer->comment != "retained constant comment") {
        std::cerr << "constant comments were not retained\n";
        return 1;
    }

    const gbrecomp::Symbol* fixed_ram = table.get_symbol(0, 0xC000);
    const gbrecomp::Symbol* banked_ram = table.get_symbol(1, 0xD000);
    if (!fixed_ram || fixed_ram->type != gbrecomp::SymbolType::DATA ||
        !banked_ram || banked_ram->type != gbrecomp::SymbolType::DATA) {
        std::cerr << "RAM symbols were not retained as data symbols\n";
        return 1;
    }
    if (fixed_ram->comment != "retained RAM comment") {
        std::cerr << "address-symbol comments were not retained\n";
        return 1;
    }

    const std::vector<std::pair<uint16_t, gbrecomp::SymbolMemorySpace>>
        memory_space_cases = {
            {0x0100, gbrecomp::SymbolMemorySpace::PHYSICAL_ROM},
            {0x8000, gbrecomp::SymbolMemorySpace::VRAM},
            {0xA000, gbrecomp::SymbolMemorySpace::EXTERNAL_RAM},
            {0xC000, gbrecomp::SymbolMemorySpace::WRAM},
            {0xD000, gbrecomp::SymbolMemorySpace::BANKED_WRAM},
            {0xE000, gbrecomp::SymbolMemorySpace::ECHO_RAM},
            {0xFE00, gbrecomp::SymbolMemorySpace::OAM},
            {0xFEA0, gbrecomp::SymbolMemorySpace::UNUSABLE},
            {0xFF00, gbrecomp::SymbolMemorySpace::MMIO},
            {0xFF80, gbrecomp::SymbolMemorySpace::HRAM},
            {0xFFFF, gbrecomp::SymbolMemorySpace::MMIO},
        };
    for (const auto& [address, expected_space] : memory_space_cases) {
        if (gbrecomp::classify_symbol_memory_space(address) != expected_space) {
            std::cerr << "incorrect memory-space classification at "
                      << std::hex << address << "\n";
            return 1;
        }
    }

    gbrecomp::AnalysisResult metadata_analysis;
    gbrecomp::apply_symbols_to_analysis(table, metadata_analysis);
    const auto ram_metadata = metadata_analysis.symbol_metadata.find(0xC000);
    const auto constant_metadata =
        metadata_analysis.constant_metadata.find("ANSWER");
    if (ram_metadata == metadata_analysis.symbol_metadata.end() ||
        ram_metadata->second.memory_space != "wram" ||
        ram_metadata->second.width != 1 ||
        constant_metadata == metadata_analysis.constant_metadata.end() ||
        constant_metadata->second.value != 0x2A ||
        constant_metadata->second.memory_space != "constant") {
        std::cerr << "semantic symbol metadata was not exported\n";
        return 1;
    }

    const gbrecomp::Symbol* canonical = table.get_symbol(0, 0x0100);
    if (!canonical || canonical->source_name != "Start") {
        std::cerr << "duplicate-address canonical selection is not deterministic\n";
        return 1;
    }
    if (canonical->source_names !=
        std::vector<std::string>({"EntryAlias", "Start"})) {
        std::cerr << "duplicate-address aliases were not preserved\n";
        return 1;
    }

    if (!gbrecomp::build_analysis_annotations(
             table, gbrecomp::SymbolAnalysisPolicy::NAMES_ONLY)
             .empty()) {
        std::cerr << "names-only symbols created analyzer boundaries\n";
        return 1;
    }
    if (gbrecomp::build_analysis_annotations(
            table, gbrecomp::SymbolAnalysisPolicy::INFER_BOUNDARIES)
            .empty()) {
        std::cerr << "infer-boundaries policy did not retain legacy behavior\n";
        return 1;
    }

    const fs::path annotations = write_fixture(
        temporary.path,
        "trusted.annotations",
        "function 00:0100 TrustedEntry\n"
        "data 00:0200 4 TrustedData\n");
    if (!table.load_annotation_file(annotations.string(), &error)) {
        std::cerr << "trusted annotation fixture failed: " << error << "\n";
        return 1;
    }
    const auto trusted = gbrecomp::build_analysis_annotations(
        table, gbrecomp::SymbolAnalysisPolicy::NAMES_ONLY);
    if (trusted.size() != 2) {
        std::cerr << "names-only policy did not retain trusted annotations\n";
        return 1;
    }
    const gbrecomp::Symbol* trusted_entry = table.get_symbol(0, 0x0100);
    if (!trusted_entry || trusted_entry->provenance != "annotation") {
        std::cerr << "trusted annotation provenance was not retained\n";
        return 1;
    }
    gbrecomp::AnalysisResult trusted_metadata;
    gbrecomp::apply_symbols_to_analysis(table, trusted_metadata);
    const auto trusted_data = trusted_metadata.symbol_metadata.find(0x0200);
    if (trusted_data == trusted_metadata.symbol_metadata.end() ||
        trusted_data->second.width != 4) {
        std::cerr << "trusted annotation width was not retained\n";
        return 1;
    }
    if (!expect_annotation_rejected(
            temporary.path,
            "overlap.annotations",
            "data 00:0200 4 First\n"
            "data 00:0202 4 Second\n",
            "Overlapping annotation") ||
        !expect_annotation_rejected(
            temporary.path,
            "cross-space.annotations",
            "data 00:7fff 2 CrossesIntoVRAM\n",
            "memory-space boundary")) {
        return 1;
    }

    if (!expect_rejected(temporary.path,
                         "missing-name.sym",
                         "00:0100\n",
                         "Malformed symbol record") ||
        !expect_rejected(temporary.path,
                         "extra-field.sym",
                         "00:0100 Start extra\n",
                         "Malformed symbol record") ||
        !expect_rejected(temporary.path,
                         "bad-bank.sym",
                         "200:0100 TooHigh\n",
                         "Malformed banked address") ||
        !expect_rejected(temporary.path,
                         "bad-offset.sym",
                         "00:10000 TooHigh\n",
                         "Malformed banked address") ||
        !expect_rejected(temporary.path,
                         "bad-token.sym",
                         "not_hex CONSTANT\n",
                         "Malformed constant value") ||
        !expect_rejected(temporary.path,
                         "wide-constant.sym",
                         "100000000 TOO_WIDE\n",
                         "Malformed constant value") ||
        !expect_rejected(temporary.path,
                         "conflicting-constant.sym",
                         "00 DUPLICATE\n01 DUPLICATE\n",
                         "Conflicting constant")) {
        return 1;
    }

    return 0;
}
